algoritmo "idade"
// Função :
// Autor :
// Data : 13/03/2014
// Seção de Declarações 
var
idade: real
n: caractere

inicio
Escreval ("ENTRE COM O NOME DO ALUNO")
Leia (n)
Escreval ("ENTRE COM A IDADE DO ALUNO")
Leia (idade)
Se idade = 18 entao
Escreva ("O ALUNO ",n)
Escreval (" É MAIOR DE IDADE")
senao
Escreva ("O ALUNO ",n)
Escreval (" É MENOR DE IDADE")
fimse
// Seção de Comandos 
fimalgoritmo
